/**
 * Spotify Playlist Export
 * Generates Spotify playlists from discovered songs
 */

import { Song } from './algolia'

export interface SpotifyTrack {
  uri: string
  name: string
  artist: string
}

/**
 * Search for a song on Spotify
 */
async function searchSpotifyTrack(
  song: string,
  artist: string,
  accessToken: string
): Promise<string | null> {
  try {
    const query = encodeURIComponent(`${song} ${artist}`)
    const response = await fetch(
      `https://api.spotify.com/v1/search?q=${query}&type=track&limit=1`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`,
        },
      }
    )

    if (!response.ok) return null

    const data = await response.json()
    const track = data.tracks?.items?.[0]
    
    return track?.uri || null
  } catch (error) {
    console.error('Spotify search error:', error)
    return null
  }
}

/**
 * Create a Spotify playlist from songs
 */
export async function createSpotifyPlaylist(
  songs: Song[],
  playlistName: string,
  accessToken: string,
  userId: string
): Promise<{ success: boolean; playlistUrl?: string; error?: string }> {
  try {
    // Create playlist
    const createResponse = await fetch(
      `https://api.spotify.com/v1/users/${userId}/playlists`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: playlistName,
          description: `Generated by TimeSlipSearch - ${playlistName}`,
          public: false,
        }),
      }
    )

    if (!createResponse.ok) {
      return { success: false, error: 'Failed to create playlist' }
    }

    const playlist = await createResponse.json()
    const playlistId = playlist.id

    // Search for tracks on Spotify
    const trackUris: string[] = []
    for (const song of songs.slice(0, 50)) { // Spotify limit
      const uri = await searchSpotifyTrack(song.song_title, song.artist, accessToken)
      if (uri) trackUris.push(uri)
    }

    if (trackUris.length === 0) {
      return { success: false, error: 'No tracks found on Spotify' }
    }

    // Add tracks to playlist
    const addResponse = await fetch(
      `https://api.spotify.com/v1/playlists/${playlistId}/tracks`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          uris: trackUris,
        }),
      }
    )

    if (!addResponse.ok) {
      return { success: false, error: 'Failed to add tracks' }
    }

    return {
      success: true,
      playlistUrl: playlist.external_urls.spotify,
    }
  } catch (error) {
    console.error('Spotify playlist creation error:', error)
    return { success: false, error: 'Unexpected error' }
  }
}

/**
 * Get Spotify authorization URL
 */
export function getSpotifyAuthURL(): string {
  const clientId = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID
  const redirectUri = encodeURIComponent(`${window.location.origin}/api/spotify/callback`)
  const scopes = encodeURIComponent('playlist-modify-private playlist-modify-public')
  
  return `https://accounts.spotify.com/authorize?client_id=${clientId}&response_type=code&redirect_uri=${redirectUri}&scope=${scopes}`
}

/**
 * Check if user has Spotify connected
 */
export function hasSpotifyToken(): boolean {
  if (typeof window === 'undefined') return false
  return localStorage.getItem('spotify_access_token') !== null
}

/**
 * Save Spotify token
 */
export function saveSpotifyToken(token: string, expiresIn: number): void {
  if (typeof window === 'undefined') return
  
  localStorage.setItem('spotify_access_token', token)
  localStorage.setItem('spotify_token_expires', (Date.now() + expiresIn * 1000).toString())
}

/**
 * Get Spotify token
 */
export function getSpotifyToken(): string | null {
  if (typeof window === 'undefined') return null
  
  const token = localStorage.getItem('spotify_access_token')
  const expires = localStorage.getItem('spotify_token_expires')
  
  if (!token || !expires) return null
  
  if (Date.now() > parseInt(expires)) {
    localStorage.removeItem('spotify_access_token')
    localStorage.removeItem('spotify_token_expires')
    return null
  }
  
  return token
}
